CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
	id_user uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	username VARCHAR(64) UNIQUE NOT NULL,
	email VARCHAR(64) UNIQUE NOT NULL,
	password VARCHAR(12) NOT NULL,
	fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_admin BOOLEAN NOT NULL DEFAULT false);